### ISSUE TITLE
E5108: Error executing lua

### ISSUE THREAD

**Issue by p4-k4** [f-person/pubspec-assist-nvim#1]
E5108: Error executing lua ...ged/pubspec-assist-nvim/lua/pubspec-assist-nvim/in
it.lua:141: Vim(mkview):E32: No file name

**Comment by f-person** [comment]
Hi! After what do you get this error?

**Comment by p4-k4** [comment]
Hi apologies for the bland issue report (I thought this plugin may be abandoned).

I'm receiving this error as soon as I call `:PubspecAssistAddDependency` then select the package I'm after.

**Comment by f-person** [comment]
I get another error – `E5108: Error executing lua ...ged/pubspec-assist-nvim/lua/pubspec-assist-nvim/json.lua:185: unexpected character '^_' at line 1 col 1`. Maybe pub.dev's API has changed. I'll check it. Thanks for the issue report!

**Comment by p4-k4** [comment]
I'd say their API has changed as this also seems to be giving errors (can also see it hasn't had any commits for a while too).

https://github.com/akinsho/dependency-assist.nvim

**Comment by f-person** [comment]
Wow, I didn't know about that package :)

**Comment by f-person** [comment]
The response from pub.dev is messed up:

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/31893391/140929403-7fc16269-cca4-406d-b62f-b8e95128b896.png">

**Comment by p4-k4** [comment]
Certainly seems to be that way! I'll add packages manually for now :)

**Comment by f-person** [comment]
@p4-k4 can you please try the latest version? It works for me now, however our error messages are a bit different so I wanna make sure it's fixed.

**Comment by p4-k4** [comment]
Hey mate, thanks. Got a different error now.

E5108: Error executing lua ...ged/pubspec-assist-nvim/lua/pubspec-assist-nvim/init.lua:142: Vim(mkview):E32: No file name

**Comment by f-person** [comment]
Your error is different actually. It can't close the window with `vim.api.nvim_win_close(win, true)` 🤔

**Comment by f-person** [comment]
What version of Neovim are you using?

**Comment by p4-k4** [comment]
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by p4-k4** [comment]
I'm unsure what I've changed but it seems to be working now!

The last issue I had is probably not related to your plugin.

Thanks for the other fix though!

**Comment by f-person** [comment]
It's good that everything is working for you now!

Thank you too! I wouldn't have noticed the other issue without your report :)
